server:
  port: 9000
  context-path: /uaa
spring:
  redis:
    database: 0
    host: 192.168.28.130
    password:
    pool:
      max-active: 2000
      max-idle: 500
      max-wait: 1000
      min-idle: 50
    port: 6379
    timeout: 3000
  application:
    name: chatbot-auth-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatbot?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
