server:
  port: 9000
  context-path: /uaa
spring:
#  redis:
#    database: 0
#    host: 192.168.28.130
#    password:
#    pool:
#      max-active: 2000
#      max-idle: 500
#      max-wait: 1000
#      min-idle: 50
#    port: 6379
#    timeout: 3000
  application:
    name: chatbot-auth-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
