server:
  port: 9000
spring:
  redis:
    database: 0
    host: 192.168.28.130
    password:
    pool:
      max-active: 2000
      max-idle: 500
      max-wait: 1000
      min-idle: 50
    port: 6379
    timeout: 3000
security:
  oauth2:
    resource:
      filter-order: 3
      id: carbon-provider-bank
      user-info-uri: http://localhost:${server.port}/user
      prefer-token-info: false
management:
  security:
    enabled: false