server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatbot?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true
  mail:
    host: smtp.qq.com
    username: 133541014@qq.com
    password: geftxeqnzjvccbcd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: chatbot-back
  #dubbo
#  dubbo:
#    application:
#      name: mymovie-rest
#    registry:
#      address: zookeeper://127.0.0.1:2181
#    protocol:
#      name: dubbo
#      port: 20881
#    scan: com.chao.mymovie.rest.service
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.chao.chatbot.back.model
logging:
  config: classpath:logback-spring.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    ip-address: true



